/*
    QGamaCore GUI C++ Library (QGamaCoreLib)
    Copyright (C) 2010  Jiri Novak <jiri.novak.2@fsv.cvut.cz>

    This file is part of the QGamaCore GUI C++ Library.

    This library is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <ui_mainwindow.h>

#include "plugin_manager/pluginmanagerdialog.h"
#include "plugin_manager/pluginmanager.h"
#include "preferences/preferencesdialog.h"
#include "preferences/qgamasettings.h"
#include "network.h"


/** Main namespace of the QGamaCore application.
  *
  * Every single class of the project is stored in this namespace so that we could avoid name conflicts
  * with the future plugins.
  */
namespace QGamaCore {

    /** Nested namespace for UI classes.
      *
      * Those are generated by 'uic' from Qt Designer's XML output .ui file.
      */
    namespace Ui {

        /** Class generated from Qt Designer's .ui file.
          *
          * It defines the appearence of QGamaCore::MainWindow.
          */
        class MainWindow : public Ui_MainWindow {};

    } // namespace Ui


    /** MainWindow implementation class.
      *
      * All the underlaying functionality for QGamaCore::Ui::MainWindow class.
      */
    class MainWindow : public QMainWindow
    {
        Q_OBJECT

        public:
            MainWindow(QWidget *parent = 0);
            ~MainWindow();

        protected:
            void changeEvent(QEvent *e);

        private:
            /// Pointer to the Qt Designer's generated class with GUI definition.
            QGamaCore::Ui::MainWindow *ui;

            /// Pointer to the QGamaCore::PluginManagerDialog.
            QGamaCore::PluginManagerDialog *pmd;
            /// Pointer to the QGamaCore::PreferencesDialog.
            QGamaCore::PreferencesDialog *pd;

            /// Reference to the QGamaCore::PluginManager.
            QGamaCore::PluginManager &pm;
            /// Reference to the QGamaCore::QGamaSettings.
            QGamaCore::QGamaSettings &settings;

            void readSettings();
            void makeConnections();

        private slots:
            void newFile();
            void pluginManagerDialog();
            void preferencesDialog();
            void openProjectsDock();
            void openOutputDock();
            void aboutQGamaDialog();
            void aboutGnuGamaDialog();
            void aboutQtDialog();
            void on_action_Toolbar_File_toggled(bool checked);
    }; // class MainWindow

} // namespace QGamaCore


#endif // MAINWINDOW_H
