/****************************************************************************
**
**    QGamaCore GUI C++ Library (QGamaCoreLib)
**    Copyright (C) 2010  Jiri Novak <jiri.novak.2@fsv.cvut.cz>
**
**    This file is part of the QGamaCore GUI C++ Library.
**
**    This library is free software; you can redistribute it and/or modify
**    it under the terms of the GNU General Public License as published by
**    the Free Software Foundation; either version 3 of the License, or
**    (at your option) any later version.
**
**    This library is distributed in the hope that it will be useful,
**    but WITHOUT ANY WARRANTY; without even the implied warranty of
**    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**    GNU General Public License for more details.
**
**    You should have received a copy of the GNU General Public License
**    along with this library; if not, write to the Free Software
**    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
**
****************************************************************************/

#ifndef QGAMACORE__MAINWINDOW_H
#define QGAMACORE__MAINWINDOW_H

#include <QMainWindow>
#include <ui_mainwindow.h>

#include "../plugins_manager/pluginsmanagerdialog.h"
#include "../plugins_manager/pluginsmanager.h"
#include "../projects_manager/projectsmanager.h"
#include "../preferences/preferencesdialog.h"
#include "../preferences/settings.h"
#include "../utils/applicationcomponentprovider.h"
#include "texteditor.h"


/** Main namespace of the QGamaCore application.
  *
  * Every single class of the project is stored in this namespace so that we could avoid name conflicts
  * with the future plugins.
  */
namespace QGamaCore {

    /** Nested namespace for UI classes.
      *
      * Those are generated by 'uic' from Qt Designer's XML output .ui file.
      */
    namespace Ui {

        /** Class generated from Qt Designer's .ui file.
          *
          * It defines the appearence of QGamaCore::MainWindow.
          */
        class MainWindow : public Ui_MainWindow {};

    } // namespace Ui


    /** MainWindow implementation class.
      *
      * All the underlaying functionality for QGamaCore::Ui::MainWindow class.
      */
    class MainWindow : public QMainWindow
    {
        Q_OBJECT

        public:
            MainWindow(QWidget *parent = 0);
            ~MainWindow();

            void updateRecentlyOpenedProjects();
            void updateRecentlyOpenedFiles();
            void increaseProjectsCount();
            void decreaseProjectsCount();
            void updateToolsMenu();

            Document* getActiveDocument();
            TextEditor* getActiveTextEditor();

        protected:
            void changeEvent(QEvent *event);
            void closeEvent(QCloseEvent *event);

        private:
            /// Pointer to the Qt Designer's generated class with GUI definition.
            QGamaCore::Ui::MainWindow *ui;

            /// Pointer to the QGamaCore::PluginManagerDialog.
            QGamaCore::PluginsManagerDialog *pmd;
            /// Pointer to the QGamaCore::PreferencesDialog.
            QGamaCore::PreferencesDialog *pd;

            /// Reference to the QGamaCore::PluginManager.
            QGamaCore::PluginsManager *pm;
            /// Reference to the QGamaCore::ProjectsManager.
            QGamaCore::ProjectsManager *prm;
            /// Reference to the QGamaCore::Settings.
            QGamaCore::Settings *settings;

            QGamaCore::ApplicationComponentProvider *acp;

            void readSettings();
            void makeConnections();
            void initializeUi();
            void openNewSubWindow(const QString &filePath, const QString &fileType, Project *project, const QString &content = "");
            QMdiSubWindow* getActiveSubWindow();
            void setActiveSubWindow(const QString &filePath);
            bool calculating;

        public slots:
            void openFile(const QString &filePath, const QString &fileType, Project *project = 0);
            void closeFile(const QString &filePath);

        private slots:
            // subwindows
            void closeSubWindow(int number);

            // callbacks
            void onSubWindowStateChanged();
            void onSubWindowActivated(QMdiSubWindow* subWindow);
            void onWindowItemClicked(QAction* action);
            void onFileClosed(const QString &fileToClose, const QString &fileType);
            void onSubWindowOpen(const QString &filePath, const QString &fileType);

            // adjusting
            void onAdjustmentSuccess(const QString xmlStream, const QString txtStream, const QString htmlStream, Document *document, AdjustmentSetting *as);
            void onAdjustmentFailure(const QString errorMessage);

            // File menu
            void newProject();
            void openProject();
            void openRecentProject(QAction *action);
            void openRecentFile(QAction *action);
            void closeProject();
            void closeAllProjects();
            void projectProperties();
            void newNetwork();
            void openFile();
            void closeFile();
            void save();
            void saveAs();
            void saveAll();
            void print();
            void updateFileMenuEntries(Project *project);

            // Edit Menu
            void pluginManagerDialog();
            void preferencesDialog();

            // View Menu
            void on_action_Toolbar_File_toggled(bool checked);
            void on_action_Toolbar_Network_toggled(bool checked);

            // Network Menu
            void solve();
            void newSetting();
            void setCalculating(bool calculating);

            // Window Menu
            void openProjectsDock();

            // About Menu
            void aboutQGamaDialog();
            void aboutGnuGamaDialog();
            void aboutQtDialog();
    }; // class MainWindow

} // namespace QGamaCore


#endif // QGAMACORE__MAINWINDOW_H
