/*
    QGamaCore GUI C++ Library (QGamaCoreLib)
    Copyright (C) 2010  Jiri Novak <jiri.novak.2@fsv.cvut.cz>

    This file is part of the QGamaCore GUI C++ Library.

    This library is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#include <Qt/QtGui>

#include "projectsmanagerimpl.h"
#include "projectstreewidget.h"
#include "../../../config.h"
#include "../utils/utils.h"
#include "../preferences/settingsimpl.h"
#include "../main_window/mainwindow.h"

#include <iostream>

using namespace QGamaCore;


// Inicialization of the private instance pointer to null.
ProjectsManagerImpl* ProjectsManagerImpl::self = 0;


/** Constructor.
  *
  * Initializes the reference to QGamaCore::Settings.
  */
ProjectsManagerImpl::ProjectsManagerImpl() : settings(SettingsImpl::instance())
{
}


/** Creates the structure of a new project.
  *
  * That consists of creating the project directory in the user home (or at the other user specified in preferences),
  * subdirectories for networks, settings and solutions and corresponding project file.
  *
  * \param[in] name         The name of the project to be created.
  * \param[in] location     The location where the project directory will be created.
  *
  * \return                 True or False, dependent whether the action was successfull or not.
  */
bool ProjectsManagerImpl::newProject(const QString &name, const QString &location)
{
    // get the pointer to the main window widget
    MainWindow *mw = qobject_cast<MainWindow*> (Utils::findTopLevelWidget("MainWindow"));

    // get the project home directory
    QDir directory(location);

    // create it if doesn't exist
    if (!directory.exists(directory.absolutePath()))
        directory.mkpath(directory.path());

    // create the project structure, inform about potencial problems
    if (!directory.mkdir(name) || !directory.mkpath(name+"/networks") || !directory.mkpath(name+"/solutions") || !directory.mkpath(name+"/settings")) {
        QMessageBox::critical( mw, QObject::tr("Project could not be created!"), QObject::tr("Probably there were insufficient permisions to create the project structure in the specified directory."));
        return false;
    }

    // create project file, inform about potencial problems
    QFile file(directory.absolutePath()+"/"+name+"/"+name.toLower()+".qgp");
    if (!file.open(QIODevice::WriteOnly)) {
        QMessageBox::critical( mw, QObject::tr("Project could not be created!"), QObject::tr("Probably there were insufficient permisions to create the project structure in the specified directory."));
        return false;
    }

    // write initial info to it
    QTextStream projectFile(&file);
    projectFile << "# This file was generated by QGama (version "+QString(QGAMA_VERSION)+")\n\n";

    // close the file
    file.close();

    return true;
}


/** Opens a project based on the information included in specified project file.
  *
  * \param[in] projectFile     The absolute path to the project file (*.qgp)
  *
  * \return                    True or False, dependent whether the action was successfull or not.
  */
bool ProjectsManagerImpl::openProject(const QString &projectFile)
{
    // get the pointer to the projects tree widget
    ProjectsTreeWidget *ptw = qobject_cast<ProjectsTreeWidget*> (Utils::findWidget("treeWidget_Projects"));

    // open the project file
    QFile file(projectFile);
    if (!file.open(QIODevice::ReadOnly))
        return false;

    // create new empty project
    Project *project = new Project;

    // get the project location and name from the projectFile absolute path
    QStringList path = projectFile.split("/");
    QString location;
    QString name;
    for (int i=0; i<path.size()-1; ++i) {
        if (i==path.size()-2) {
            name = path[i];
            continue;
        }
        location.append(path[i]);
        if (i!=path.size()-3)
            location.append("/");
    }
    project->setLocation(location+"/");
    project->setName(name);
    project->setProjectFilePath(projectFile);

    // have a look if the project wasn't already open
    bool found = false;
    for (int i=0; i<projects.size(); ++i) {
        if (projects[i]->getName() == name && projects[i]->getLocation() == location && projects[i]->isOpened()) {
            found = true;
            break;
        }
    }

    // if wasn't already opened, process its projectFile and open it
    if (!found) {
        // read the project specifications
        QTextStream projectFile(&file);
        QString line;
        while (!projectFile.atEnd()) {
            // get the trimmed line
            line = projectFile.readLine().trimmed();

            // if deals the comment, we will skip it
            if (line[0] == '#')
                continue;
            // otherwise start to process information

        }

        // close the file
        file.close();

        // add project expandable item
        QTreeWidgetItem *itemProject = new QTreeWidgetItem(ptw);
        itemProject->setText(0,project->getName());
        itemProject->setText(1,"projectName");
        itemProject->setText(2,project->getLocation());
        itemProject->setIcon(0,QIcon(":/images/icons/babieca-64.png"));
        itemProject->setExpanded(true);

        // add networks, solutions, settings expandable item and non expandable projectFile item
        QTreeWidgetItem *itemProjectFile = new QTreeWidgetItem(itemProject);
        QTreeWidgetItem *itemNetworks = new QTreeWidgetItem(itemProject);
        QTreeWidgetItem *itemSolutions = new QTreeWidgetItem(itemProject);
        QTreeWidgetItem *itemSettings = new QTreeWidgetItem(itemProject);

        // set corresponding texts and icons
        itemProjectFile->setText(0,project->getName().toLower()+".qgp");
        itemProjectFile->setText(1,"projectFile");
        itemProjectFile->setIcon(0,QIcon(":/images/icons/notes-32.png"));

        itemNetworks->setText(0,QObject::tr("Networks"));
        itemNetworks->setIcon(0,QIcon(":/images/icons/standardbutton-open-32.png"));

        itemSolutions->setText(0,QObject::tr("Settings"));
        itemSolutions->setIcon(0,QIcon(":/images/icons/standardbutton-open-32.png"));

        itemSettings->setText(0,QObject::tr("Solutions"));
        itemSettings->setIcon(0,QIcon(":/images/icons/standardbutton-open-32.png"));

        // append project to the list of projects, set the open property and mark it as active
        projects.append(project);
        project->setOpened(true);
        ptw->changeActiveProject(itemProject,0);

        // disable the transparent background
        ptw->setStyleSheet("");

        // save the project to be opened next time program is executed
        QStringList openedProjects = settings.get("projects/openedProjects").toStringList();
        if (!openedProjects.contains(project->getProjectFilePath())) {
            openedProjects.append(project->getProjectFilePath());
            settings.set("projects/openedProjects",openedProjects);
        }
    }

    // if was already opened
    else {
        // change the focus to it
        QTreeWidgetItem *item = 0;
        for (int i=0; i<ptw->topLevelItemCount(); ++i) {
             item = ptw->topLevelItem(i);
             if (item->text(0) == project->getName()) {
                ptw->changeActiveProject(item,0);
             }
        }

        // delete the temporary project, we have created
        delete project;
    }

    return true;
}


/**
  *
  */
void ProjectsManagerImpl::closeProject(Project* project)
{
    // get the pointer to the projects tree widget
    ProjectsTreeWidget *ptw = qobject_cast<ProjectsTreeWidget*> (Utils::findWidget("treeWidget_Projects"));

    // delete the project tree widget entries
    QTreeWidgetItem *item = 0;
    for (int i=0; i<ptw->topLevelItemCount(); ++i) {
         item = ptw->topLevelItem(i);
         if (item->text(0)==project->getName()) {
             delete ptw->takeTopLevelItem(i);
             break;
         }
    }

    // save the project to be opened next time program is executed
    QStringList openedProjects = settings.get("projects/openedProjects").toStringList();
    for (int i=0; i<openedProjects.size(); i++) {
        if (openedProjects[i]==project->getProjectFilePath()) {
            openedProjects.removeAt(i);
            break;
        }
    }
    if (openedProjects.size()>0) {
        settings.set("projects/openedProjects",openedProjects);
    }
    else {
        settings.del("projects/openedProjects");
    }

    // delete the project
    for (int i=0; i<projects.size(); i++) {
        if (projects[i]==project) {
            projects.removeAt(i);
        }
    }
    delete project;

    // grey out the area, if we have just closed the last project
    if (ptw->topLevelItemCount()==0)
        ptw->setStyleSheet("background-color: transparent;");
}


void ProjectsManagerImpl::closeActiveProject()
{
    closeProject(activeProject());
}


Project* ProjectsManagerImpl::activeProject()
{
    for (int i=0; i<projects.size(); i++) {
        if (projects[i]->isActive()) {
            return projects[i];
        }
    }

    return 0;
}


void ProjectsManagerImpl::setActiveProject(const QString &name, QString location)
{
    for (int i=0; i<projects.size(); i++) {
        if (projects[i]->getName()==name && projects[i]->getLocation()==location) {
            projects[i]->setActive(true);
         }
        else
            projects[i]->setActive(false);
    }
}
