/*
    QGamaCore GUI C++ Library (QGamaCoreLib)
    Copyright (C) 2010  Jiri Novak <jiri.novak.2@fsv.cvut.cz>

    This file is part of the QGamaCore GUI C++ Library.

    This library is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#include <QDir>
#include <QString>
#include <QIODevice>
#include <QTextStream>
#include <QFile>
#include <QMenu>
#include <QAction>
#include <QList>
#include <QMessageBox>
#include <QApplication>

#include "projectsmanagerimpl.h"
#include "projectstreewidget.h"
#include "../../../config.h"
#include "../utils/utils.h"
#include "../preferences/settingsimpl.h"
#include "../main_window/mainwindow.h"

#include <iostream>

using namespace QGamaCore;


// Inicialization of the private instance pointer to null.
ProjectsManagerImpl* ProjectsManagerImpl::self = 0;


/**
  *
  */
ProjectsManagerImpl::ProjectsManagerImpl() : settings(SettingsImpl::instance())
{
}


/**
  *
  */
bool ProjectsManagerImpl::newProject(const QString &name, const QString &location, bool mainProject)
{
    // get the pointer to the main window widget
    MainWindow *mw = qobject_cast<MainWindow*> (Utils::findTopLevelWidget("MainWindow"));

    // get the project home directory
    QDir directory(location);

    // create it if doesn't exist
    if (!directory.exists(directory.absolutePath()))
        directory.mkpath(directory.path());

    // create the project structure
    if (!directory.mkdir(name) || !directory.mkpath(name+"/networks") || !directory.mkpath(name+"/solutions") || !directory.mkpath(name+"/protocols")) {
        QMessageBox::critical( mw, QObject::tr("Project could not be created!"), QObject::tr("There were insufficient permisions to create the project structure in the specified directory."));
        return false;
    }

    // create project file
    QFile file(directory.absolutePath()+"/"+name+"/"+name.toLower()+".qgp");
    if (!file.open(QIODevice::WriteOnly)) {
        QMessageBox::critical( mw, QObject::tr("Database Error"), QObject::tr("Nepodarilo se spojit s databazi. Aplikace bude ukoncena.") );
        return false;
    }

    // write initial info to it
    QTextStream projectFile(&file);
    projectFile << "# This file was generated by QGama (version "+QString(QGAMA_VERSION)+")\n\n";
    projectFile << "# General Project Information:\n";
    if (mainProject)
        projectFile << "project.main=yes\n";
    else
        projectFile << "project.main=no\n";
    file.close();

    return true;
}


/**
  *
  */
bool ProjectsManagerImpl::openProject(const QString &projectFile)
{
    // get the pointer to the projects tree widget
    ProjectsTreeWidget *ptw = qobject_cast<ProjectsTreeWidget*> (Utils::findWidget("treeWidget_Projects"));

    // get the pointer to the main window widget
    MainWindow *mw = qobject_cast<MainWindow*> (Utils::findTopLevelWidget("MainWindow"));

    // enable projects tree widget if already isn't
    if (!ptw->isEnabled())
        ptw->setEnabled(true);

    // open the project file
    QFile file(projectFile);
    if (!file.open(QIODevice::ReadOnly)) {
        QMessageBox::critical(mw , QObject::tr("Project could not be opened!"), QObject::tr("Maybe there are insufficient permisions read the project file.") );
        return false;
    }

    // create new project
    Project *project = new Project;

    // get the project location and name from the projectFile absolute path
    QStringList path = projectFile.split("/");
    QString location;
    QString name;
    for (int i=0; i<path.size()-1; ++i) {
        if (i==path.size()-2) {
            name = path[i];
            continue;
        }
        location.append(path[i]);
        if (i!=path.size()-3)
            location.append("/");
    }
    project->setLocation(location);
    project->setName(name);

    // have a look if the project wasn't already open
    bool found = false;
    for (int i=0; i<projects.size(); ++i) {
        if (projects[i]->getName() == name && projects[i]->getLocation() == location && projects[i]->isOpened()) {
            found = true;
            break;
        }
    }

    // if wasn't already opened, we will process its projectFile and open it
    if (!found) {
        // read the project specifications
        QTextStream projectFile(&file);
        QString line;
        while (!projectFile.atEnd()) {
            // get the trimmed line
            line = projectFile.readLine().trimmed();

            // if deals the comment, we will skip it
            if (line.at(0) == '#')
                continue;
            // otherwise start to process information
            else if (line.startsWith("project.main=")) {
                if (line.split("=").value(1).trimmed() == "yes")
                    project->setMainProject(true);
                else if (line.split("=").value(1).trimmed() == "no")
                    project->setMainProject(false);
            }
        }

        // close the file
        file.close();

        // add project expandable item
        QTreeWidgetItem *itemProject = new QTreeWidgetItem(ptw);
        itemProject->setText(0,project->getName());
        itemProject->setText(1,"projectName");           // data
        itemProject->setText(2,project->getLocation());  // data
        itemProject->setIcon(0,QIcon(":/images/icons/babieca-64.png"));
        itemProject->setExpanded(true);
        itemProject->setSelected(true);
        ptw->changeActiveProject(itemProject,0);

        // add networks, solutions, protocols expandable item and non expandable projectFile item
        QTreeWidgetItem *itemNetworks = new QTreeWidgetItem(itemProject);
        QTreeWidgetItem *itemSolutions = new QTreeWidgetItem(itemProject);
        QTreeWidgetItem *itemProtocols = new QTreeWidgetItem(itemProject);
        QTreeWidgetItem *itemProjectFile = new QTreeWidgetItem(itemProject);

        // set corresponding texts and icons
        itemNetworks->setText(0,QObject::tr("Networks"));
        itemNetworks->setIcon(0,QIcon(":/images/icons/standardbutton-open-32.png"));

        itemSolutions->setText(0,QObject::tr("Solutions"));
        itemSolutions->setIcon(0,QIcon(":/images/icons/standardbutton-open-32.png"));

        itemProtocols->setText(0,QObject::tr("Protocols"));
        itemProtocols->setIcon(0,QIcon(":/images/icons/standardbutton-open-32.png"));

        itemProjectFile->setText(0,project->getName().toLower()+".qgp");
        itemProjectFile->setText(1,"projectFile");      // data
        itemProjectFile->setIcon(0,QIcon(":/images/icons/notes-32.png"));
        
        project->setOpened(true);
        projects.append(project);
    }

    // if was already opened
    else {
        QTreeWidgetItem *item = 0;
        for (int i=0; i<ptw->topLevelItemCount(); ++i) {
             item = ptw->topLevelItem(i);
             if (item->text(0) == project->getName()) {
                ptw->changeActiveProject(item,0);
             }
        }

        delete project;
    }

    return true;
}
